params{
 FQ_PAIR_RADICAL="R"
 FQ_COMPRESSION_EXTENSION=".gz"
 FQ_FILE_EXTENSION=".fastq"
 RAWDIR="/data/users/ltaing/DATA_TMP/ltaing/IsoAndSpe/NotToBeAlteredFiles/FASTQ/"
 FASTA="/data/users/ltaing/DATA_TMP/ltaing/IsoAndSpe/Ressources/GRCh38.p12.genome.fa"
 GTF="/data/users/ltaing/DATA_TMP/ltaing/IsoAndSpe/Ressources/gencode.v28.annotation.gtf"
 scallop="/bioinfo/users/ltaing/DATA_TMP/ltaing/COMPARE_ISO/scallop"
 strawberry="/bioinfo/users/ltaing/DATA_TMP/ltaing/COMPARE_ISO/strawberry1.0.2"
 Trial_Dir="RefAbsolute"
 style="OnePass"
 seed=47
  Spectro{
    RAW_Files_DIRECTORY="/bioinfo/users/ltaing/DATA_TMP/ltaing/IsoAndSpe/NotToBeAlteredFiles/RAW"
    SampleDescriptionFile="/data/tmp/ltaing/IsoAndSpe/NotToBeAlteredFiles/MassSpec.Local.SampleDescription.txt"
    TemplateMqparFile="/data/tmp/ltaing/IsoAndSpe/NotToBeAlteredFiles/mqpar.Celine_4T.Prototype.xml"
    MaxQuant="/bioinfo/users/ltaing/SOFTS/MaxQuantVersion1.6.2.6/bin/MaxQuantCmd.exe"
    MonoSIMG="/bioinfo/users/ltaing/mono-5.16.0.220.simg"
 }
}

profiles {
  standard {
    process.executor = 'local'
    beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
  }
  cluster {
    process {
      withLabel: Mapping {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'pbs'
        scratch = 'true'
        stageInMode = 'copy'
        stageOutMode = 'move'
        cpus = 8
        memory = 64.GB
      }
      withLabel: Sort {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'pbs'
        scratch = 'true'
        stageInMode = 'copy'
        stageOutMode = 'move'
        cpus = 12
        memory = 36.GB
      }
      withLabel: Convert {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'pbs'
        scratch = 'true'
        stageInMode = 'copy'
        stageOutMode = 'move'
        cpus = 1
        memory = 8.GB
      }
      withLabel: Isoform {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'local'
      }
      withLabel: hstbld {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'pbs'
        scratch = 'true'
        stageInMode = 'copy'
        stageOutMode = 'move'
        cpus = 1
        memory = 256.GB
      }
      withLabel: huge {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'pbs'
        scratch = 'true'
        stageInMode = 'copy'
        stageOutMode = 'move'
        cpus = 10
        memory = 200.GB
      }
      withLabel: small {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'pbs'
        scratch = 'true'
        stageInMode = 'copy'
        stageOutMode = 'move'
        cpus = 5
        memory = 20.GB
      }
      withLabel: spectro{
        beforeScript = "source /data/users/${LOGNAME}/.bashrc"
        scratch = 'true'
        afterScript = "sleep 5m"
        cpus = 16
        time = '21d'
        memory = 126.GB
        executor = 'pbs'
      }
      withLabel: OneSmall {
        beforeScript = "source /data/users/${LOGNAME}/.bashrc" 
        executor = 'pbs'
        scratch = 'true'
        stageInMode = 'copy'
        stageOutMode = 'move'
        cpus = 1
        memory = 24.GB
      }
    }
  }
}

executor {
    name = 'pbs'
    queueSize = 20
    pollInterval = '30 sec'
}


conda {
    createTimeout = '60 min'
    cacheDir = "/bioinfo/users/ltaing/CondaCache"
}

